import React from "react";
import { Metadata } from "next";
import LoginPage from "@/components/views/LoginPage";
export const metadata: Metadata = {
  title: "Login page",
  description: "Generated by create next app",
};

const Index = () => {
  return <LoginPage />;
};

export default Index;
