import QuestionStart from "@/app/user/tests/home/[userTestId]/question/(component)/QuestionStart";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Question",
  description: "Generated by create next app",
};
const Page = () => {
  return <QuestionStart />;
};

export default Page;
