import QuestionStart from "@/app/user/tests/home/[userTestId]/question/(component)/QuestionStart";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Question",
  description: "Generated by create next app",
};
const Page = () => {
  return (
    <div className="p-4 sm:p-0">
      <QuestionStart />
    </div>
  );
};

export default Page;
