import React from "react";
import { Metadata } from "next";
import ForgotPassword from "@/components/views/ForgotPassword";

export const metadata: Metadata = {
  title: "Forgot password page",
  description: "Generated by create next app",
};

const Index = () => {
  return <ForgotPassword />;
};

export default Index;
