import React from "react";
import { Metadata } from "next";
import CheckEmail from "@/components/views/CheckEmail";

export const metadata: Metadata = {
  title: "Check email page",
  description: "Generated by create next app",
};

const Index = () => {
  return <CheckEmail />;
};

export default Index;
