import React from "react";
import { Metadata } from "next";
import ResetPassword from "@/components/views/ResetPassword";
export const metadata: Metadata = {
  title: "Reset password page",
  description: "Generated by create next app",
};

const Index = () => {
  return <ResetPassword />;
};

export default Index;
