import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import TanstackWrapper from "@/lib/tanstack.wrapper";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <body className={poppins.className}>
      <TanstackWrapper>{children}</TanstackWrapper>
    </body>
  </html>
);

export default RootLayout;
