import type { Metadata } from "next";
import "../../../../globals.css";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "User Test ID",
  description: "Generated by create next app",
};

export default function IDLayout({ children }: React.PropsWithChildren) {
  return <div className="p-10">{children}</div>;
}
