import HomeComponent from "@/app/user/tests/home/(component)/HomeComponent";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "User Test",
  description: "Generated by create next app",
};

const HomePage = () => {
  return (
    <div className="p-10 sm:p-0 ">
      <HomeComponent />
    </div>
  );
};

export default HomePage;
