import HomeComponent from "@/app/user/tests/home/(component)/HomeComponent";
import { Metadata } from "next";
import Image from "next/image";
import React from "react";
export const metadata: Metadata = {
  title: "User Test",
  description: "Generated by create next app",
};

const HomePage = () => {
  return (
    <>
      <Image alt="logo" width={200} height={100} src={"/logo.png"} />
      <HomeComponent />
    </>
  );
};

export default HomePage;
