import Welcome from "@/app/user/tests/(component)/Welcome";
import { Metadata } from "next";
import Image from "next/image";
import React from "react";
type TProps = {};
export const metadata: Metadata = {
  title: "User Test",
  description: "Generated by create next app",
};
const page = (props: TProps) => {
  return (
    <>
      <Image alt="logo" width={200} height={100} src={"/logo.png"} />
      <div className="flex items-center justify-center">
        <Welcome />
      </div>
    </>
  );
};

export default page;
